# Generated by Django 4.1.5 on 2023-01-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="products/", null=True, upload_to="products/"
            ),
        ),
    ]
